# List of stdueis and their run types
# Run types are separated by a "_"
# If no run type is given (e.g. GSE12345)
# The the default parameters are used as thne "plain" run
studies:
  - GSE139910
  - GSE37744_dedup  
  
# If False, then the system halts if the pre-run checks fail
# If True, RiboFlow is run regardless of pre-run checks 
override: False

riboflow_config: stampede_local
adapter_threshold: 50
threads: # specify number of threads to give each rule
    download_fastq_files: 6
    gzip_fastq: 1
    check_adapter: 4
    check_adapter_stats: 1
    check_lengths: 1
    run_riboflow: 48
check_adapter:
    skipped_reads: 1000000 # default is 1,000,000 reads
    sample_size: 25000 # default is 25,000 reads
guess_adapter:
    skipped_reads: 1000000 # default is 1,000,000 reads
    sample_size: 10000 # default is 10,000 reads 
    min_length: 10 # specifies the minimum length for a valid adapter guess, default is 10 
    max_length: 15 # specifies when to stop extending adapter guess, default is 15 
    skipped_nucleotides: 10 # specifies number of nucleotides to skip within a read, since we are guessing the 3' adapter, default is 10
    seed_length: 6 # specifies the initial seed length to begin extending from, default is 6
    match_ratio: 0.5 # extend the candidate adapter sequence by 1 nt if there is a single base that appears at or more than this fraction, default is 0.5
    

