$schema: 'http://json-schema.org/draft-07/schema#'
description: Schema for Project.Yaml Input
type: object
properties:
  override:
    type: boolean
    default: false
    description: Setting to Override Any Exceptions Thrown during Pre-Run Checks and Run RiboFlow
  adapter_threshold:
    type: integer
    default: 50
  riboflow_config:
    type: string
    description: Config Setting Used for RiboFlow
  studies:
    description: List of Studies to be Processed
    type: array
    items:
      type: string
    description: boolean that indicates if sample is case or control
  threads:
    type: object
    properties:
      download_fastq_files: 
        default: 6 
        type: integer
      gzip_fastq:
        default: 1 
        type: integer
      check_adapter:
        default: 4
        type: integer
      check_adapter_stats:
        default: 1
        type: integer
      check_lengths:
        default: 1 
        type: integer
      run_riboflow:
        type: integer
  check_adapter:
    type: object
    properties:
      skipped_reads:
        default: 1000000
        type: integer
      sample_size:
        default: 25000
        type: integer
  guess_adapter:
    type: object
    properties:
      skipped_reads:
        default: 1000000
        type: integer
      sample_size:
        default: 10000
        type: integer
      min_length:
        default: 10 
        type: integer
      max_length:
        default: 15
        type: integer
      skipped_nucleotides:
        default: 10
        type: integer
      seed_length:
        default: 6
        type: integer
      match_ratio:
        default: 0.5
        type: number
    
required:
  - studies
  - riboflow_config
  - threads